### ISSUE TITLE
Too many connection attempts to Home Assistant

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#114]
Which result in a continuous spam of log entries of the form:
```
Error on Home Assistant websocket: Error: socket hang up
```

**Comment by pvizeli** [comment]
It would be nice if we can make the retry to 10s for a long time. They spam now also the supervisor.

**Comment by gcampax** [comment]
I haven't seen this happen for a while: we try connecting 10 times and then bail. Closing.
