### ISSUE TITLE
Unknown developer key

### ISSUE THREAD

**Issue by anuragkumar95** [stanford-oval/thingpedia-common-devices#174]
I am trying to run almond and I have been closely following the tutorial on Almond website. However, nowhere in the tutorial, ways to get a developer key, is mentioned. 

```
make release=$release subdatasets=1 target_pruning_size=25 max_turns=2 debug_level=2 datadir
```
errors out with the following messsage,

```
node_modules/.bin/thingpedia --url https://almond-dev.stanford.edu/thingpedia --developer-key invalid --access-token invalid \
download-entity-values --manifest parameter-datasets.tsv.tmp --append-manifest -d parameter-datasets
100%  [==============================] - 29s
node_modules/.bin/thingpedia --url https://almond-dev.stanford.edu/thingpedia --developer-key invalid --access-token invalid \
download-string-values --manifest parameter-datasets.tsv.tmp --append-manifest -d parameter-datasets
0%  [..............................] - ETA: 0s
HTTP request failed: {"error":"A valid developer key is required to download string datasets","code":"EPERM"
{ Error: Unexpected HTTP error 403
       at IncomingMessage.res.on (/home/anurag/thingpedia-common- 
       devices/node_modules/thingpedia/lib/helpers/http.js:111:33)
       at IncomingMessage.emit (events.js:203:15)
       at endReadableNT (_stream_readable.js:1145:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
  detail:
      '{"error":"A valid developer key is required to download string datasets","code":"EPERM"}',
  code: 403 } 
Makefile:148: recipe for target 'parameter-datasets.tsv' failed 
```

Is there a link with steps on getting a new developer's key??

**Comment by gcampax** [comment]
What tutorial is this? You should probably follow the new guide at https://wiki.almond.stanford.edu/thingpedia because it's more up to date.

You get a developer key when you create a developer account from the link https://almond-dev.stanford.edu/user/request-developer
(note: the link refers to our development/test server, which is not stable and will be wiped periodically, don't use that account to submit Thingpedia devices or store anything valuable)

**Comment by gcampax** [comment]
From the other issues, I'm going to assume you now know to how get a dev key, and close this.
