### ISSUE TITLE
"Kpop" is not recognized as a valid genre

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#182]
"play some kpop" returns no songs, but "play some k-pop" works.

Not sure if the problem is in the Spotify API or in ThingTalk's `contains~`

**Comment by ryachen01** [comment]
"Kpop" isn't a genre, so this should be fixed with https://github.com/stanford-oval/thingtalk/pull/252

**Comment by gcampax** [comment]
Let's add it as a test there to be sure.
