### ISSUE TITLE
New command: "add this song to my library"

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#183]
When a question like "what's the most popular song on Spotify" turns out something good, we should let the user add it to the library (which influences Spotify's recommendation algorithm).

**Comment by tonyespinoza1** [comment]
@jmhw0123 need clarification on what is implemented here.  how do i test it?

![image](https://user-images.githubusercontent.com/86493411/129388881-fdece8b4-4252-44f2-b4c8-4eb24aff6cbe.png)

**Comment by gcampax** [comment]
This was implemented as designed.
