### ISSUE TITLE
Translation almond

### ISSUE THREAD

**Issue by pretendor91** [stanford-oval/thingpedia-common-devices#199]
Hello foks,

I will issue this. It isn’t any bug or something like that. I would aak you for the files which are used to command almond/ada.
I noticed it was in english and i would like to translate all available commands to dutch. 
So my little kid is able to change the light color or turn on the light in her bedroom.

I hope to hear from you. And yes once i translate everything i would share this with you all :)

**Comment by nrser** [comment]
Thank you for your interest! Supporting additional languages is very important to us, but we don't yet have any tools, documentation or support for introducing a new language. Genie is a machine learning system, and the way it understands a language and synthesizes the training data it needs is sophisticated.

If you look through this repository a the `manifest.tt` and `dataset.tt` files, that will give you an idea of one part of what is needed.

The other necessary part is a corresponding `.po` file (gettext file) like the ones here, containing all the constructs that combine the short phrases in this repo to form full dialogues:
https://github.com/stanford-oval/genie-toolkit/tree/master/po
