### ISSUE TITLE
Error in bing search

### ISSUE THREAD

**Issue by bfapps** [stanford-oval/thingpedia-common-devices#217]
Every time I try searching something on Bing. It returns:
Sorry, that did not work: Unexpected HTTP error 401.

**Comment by gcampax** [comment]
Hi thanks for this bug report! It looks like it is a problem with subscription key used to contact Bing. What version of Almond did this occur with, or what Almond site?

**Comment by gcampax** [comment]
Thanks for the info. I will take a look, and update the API key if necessary.

**Comment by gcampax** [comment]
Thanks again for the report. It looks like the Bing skill was using a version of the Bing that is no longer available. I have updated it to the latest version and it seems to work again. On the website it will take up to 24 hours for the new version to propagate. Locally, you go into My Skill, find the Bing skill, and click "Check for update". Restart Almond if the update does not appear to take effect.
