### ISSUE TITLE
Add support for podcasts and playlists in the Spotify skill

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#226]
This is a tracking issue for those two features.

**Comment by AydanPirani** [comment]
Working on this as of now, will be incorporated in PR #227

**Comment by AydanPirani** [comment]
@gcampax Is this movable to "Reviewer Approved" or "Testing"?

**Comment by gcampax** [comment]
Yeah, the PR was merged so this can be closed. The automation will move the card accordingly.
