### ISSUE TITLE
Prefer songs to albums when both exist with the same name

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#270]
From the logs:
```
U: play yellow brick road by elton john
UT: $dialogue @org.thingpedia.dialogue.transaction.execute;
UT: @com.spotify.playable() filter contains(artists, null^^com.spotify:artist("elton john")) && id =~ "yellow brick road" => @com.spotify.play(playable=id);
C: $dialogue @org.thingpedia.dialogue.transaction.execute;
C: (@com.spotify(id="com.spotify-gcampax"^^tt:device_id("Spotify Account of gcampax")).playable() filter contains(artists, "spotify:artist:3PhoLpVuITZKcymswpck5b"^^com.spotify:artist("Elton John")) && id =~ "yellow brick road")[1] => @com.spotify(id="com.spotify-gcampax"^^tt:device_id("Spotify Account of gcampax")).play(playable=id)
C: #[results=[
C:   { device="b305db3b61d1c95661290444e9ddef901ccfff60"^^com.spotify:device("giovanni-xps15"), playable="spotify:album:5WupqgR68HfuHt3BMJtgun"^^com.spotify:playable("Goodbye Yellow Brick Road (Remastered)") }
C: ]];
A: I played Goodbye Yellow Brick Road (Remastered) on Spotify.
AT: $dialogue @org.thingpedia.dialogue.transaction.sys_action_success;
```

It played the album (which starts with a different song) and not the song. This is confusing, and makes it seem like the agent is misbehaving.

**Comment by ryachen01** [comment]
I'm not sure if we should always default to songs over albums when both exist with the same name because there are a lot of albums and songs with the same name. If we do this and say "play the wall" then we'd end up playing some random song instead of the album. Right now, we're just returning the most popular song or album that matches. How do we want to handle this?

**Comment by gcampax** [comment]
Mh I see. Maybe prefer a song to an album if both exist by the same artist (or where artists overlap)? Cause refining by artist name is somewhat intuitive if we play the wrong thing with the right name, but refining to say "song" or "album" is less intuitive, I'm seeing from the logs.
