### ISSUE TITLE
Bad error message for missing definitions in Owlbot

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingpedia-common-devices#277]
Currently, if Owlbot doesn't know a word, the agent replies with "Request failed with status code 404", which is not nice. We should catch that error and show a more informative error message.

**Comment by AydanPirani** [comment]
Resolving.

**Comment by gcampax** [comment]
That's not what I see:
![screenshot of owlbot skill, the agent replies with "Sorry, Request failed with status code 404."](https://user-images.githubusercontent.com/876889/110547289-9673c380-80e4-11eb-8846-73cac0f74c46.png)

This is on dev.almond.stanford.edu with the latest version of the skill.
