### ISSUE TITLE
(Staging) Enhancement: ability to "like" songs, podcasts, albums and artists

### ISSUE THREAD

**Issue by tonyespinoza1** [stanford-oval/thingpedia-common-devices#383]
Capturing this feature request for discussion.  I see it's not in the cheatsheet.

"like"
"love"
"favorite"
"remember"
"save"
"keep"

"X this"
"i X this"
"X this song"
"X this artist"
"X this album"
"X this podcast"

**Comment by gcampax** [comment]
Related issue: https://github.com/stanford-oval/thingpedia-common-devices/issues/183

(same feature, different way of phrasing it)

**Comment by jmhw0123** [comment]
Let's leave `artists` out of this for now.

**Comment by tonyespinoza1** [comment]
@jmhw0123 

is "like this artist" difficult to implement?  if so, i'd be interested to learn why.

**Comment by tonyespinoza1** [comment]
I want to clarify the feature request here.

The concept would be that a piece of content or container (artist, album) may be "liked" by using the following keywords:

"like"
"love"
"favorite"
"remember"
"save"
"keep"

In the following contexts:

"X this"
"i X this"
"X this song"
"X this artist"
"X this album"
"X this podcast"

***whilst the song is playing.**

@jmhw0123 can you clarify what aspect of this is "ready for qa" since i am unable to get it to work and suspect you have implemented something different than above.

**Comment by tonyespinoza1** [comment]
this is what i'm currently seeing: 

![image](https://user-images.githubusercontent.com/86493411/129388642-f8d618c2-f8bb-4c11-ac5f-2f54a8ae59aa.png)

**Comment by jmhw0123** [comment]
I think we need to add annotated data for the model to learn

**Comment by tonyespinoza1** [comment]
it's possible we don't have your code in our build on staging right now as well... @nrser is trying to work it out now. @kevintangzero: could you work with @jmhw0123 and figure out if we need to add annotations?

**Comment by nrser** [comment]
Liking songs works pretty well for me, but I tried "like this album" and it just liked the song again

**Comment by nrser** [comment]
@jmhw0123 is this one that should be improved by more annotated data?

**Comment by tonyespinoza1** [comment]
@jmhw0123 should this work?

```
====
# main/8a3f1009-2d90-4e60-a7ef-a9007f445d5e
#! timestamp: 2021-09-09T01:46:34.084Z
U: play podcast
UT: $dialogue @org.thingpedia.dialogue.transaction.execute;
UT: @org.thingpedia.media-source.show() => @org.thingpedia.media-player.play(playable=id);
C: $dialogue @org.thingpedia.dialogue.transaction.execute;
C: @org.thingpedia.media-source(id="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza")).show() => @org.thingpedia.media-player(id="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza")).play(playable=id)
C: #[results=[
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony’s Mac Pro"), playable="spotify:show:5ZKHbyeo97VivPN05bXt8r"^^org.thingpedia.media-source:playable("Good Times with Mo: The Podcast Year 10"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony’s Mac Pro"), playable="spotify:show:1TZWDLIrcaPgq7kQAyOqfQ"^^org.thingpedia.media-source:playable("Year End Reflection"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony’s Mac Pro"), playable="spotify:show:3CpR3dGT55X7ZxUfJ0mS7S"^^org.thingpedia.media-source:playable("Come Follow Me 2021 - Doctrine and Covenants"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony’s Mac Pro"), playable="spotify:show:1d2Arg2uau2W6JXcY4gNqR"^^org.thingpedia.media-source:playable("20 Years of 24"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") },
C:   { device="93f56161fd84ab2dffb3387154e75d2199d1de46"^^org.thingpedia.media-player:device("Tony’s Mac Pro"), playable="spotify:show:21JT1fT5BauYygwzWhXqzm"^^org.thingpedia.media-source:playable("Commencement: Speeches For The Class of 2021"), __device="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza") }
C: ]];
#! timestamp: 2021-09-09T01:46:36.311Z
A: I played shows on Spotify for you.
AT: $dialogue @org.thingpedia.dialogue.transaction.sys_action_success;
#! timestamp: 2021-09-09T01:46:39.617Z
U: like this podcast
UT: $dialogue @org.thingpedia.dialogue.transaction.execute;
UT: @org.thingpedia.media-source(id="com.spotify-126743886"^^tt:device_id("Spotify Account of Tony Espinoza")).get_currently_playing() => @com.spotify.add_item_to_library(playable=id);
```
![image](https://user-images.githubusercontent.com/86493411/132608659-f98376b1-78bd-4139-b469-5a35c3b44f26.png)

**Comment by jmhw0123** [comment]
Works fine on my side
![image](https://user-images.githubusercontent.com/51076115/133050132-f29e8e7e-a2e7-4507-8bbf-eb80645414bf.png)

**Comment by tonyespinoza1** [comment]
working for me too now!
