### ISSUE TITLE
(Staging) Cannot read property'thumbnailUrl' of undefined from simple bing query

### ISSUE THREAD

**Issue by tonyespinoza1** [stanford-oval/thingpedia-common-devices#400]
ask bing who invented algebra

Sorry, I had an error processing your command: Cannot read property'thumbnailUrl' of undefined.

```
====
# main/45265f70-9b14-4999-a58a-6325182d7bbb
#! timestamp: 2021-07-29T02:21:36.485Z
U: ask bing who invented algebra
UT: @com.bing.entities;
```

**Comment by gcampax** [comment]
@jmhw0123 can you take a look at this one? should just be a matter of being defensive in handling bing answers because they don't always conform to their documented schema
