### ISSUE TITLE
Weather response edit

### ISSUE THREAD

**Issue by tonyespinoza1** [stanford-oval/thingpedia-common-devices#436]
Let's remove the time from this response.

Response should be: "It will be cloudy next Sunday in San Francisco, California and the temperature will be 61 F."
![image](https://user-images.githubusercontent.com/86493411/133172603-07924b81-3b83-4f75-a74b-806da5ac6705.png)

```
====
# main/72e7b2b3-f242-4a40-9801-91ae993a29bc
#! timestamp: 2021-09-14T00:05:34.859Z
U: what's the weather next week in san francisco?
UT: $dialogue @org.thingpedia.dialogue.transaction.execute;
UT: @org.thingpedia.weather.forecast(date=$end_of(week), location=new Location("san francisco"));
```

**Comment by gcampax** [comment]
This was fixed at some point.
