### ISSUE TITLE
upload all the manifest.tt and dataset.tt files

### ISSUE THREAD

**Issue by rayslxu** [stanford-oval/thingpedia-common-devices#63]

**Comment by gcampax** [comment]
I have all the manifest.tt, but not the dataset.tt.
I forgot about those...

**Comment by elvisyjlin** [comment]
It will be helpful for us to do the Chinese translation if the datasets are uploaded! So that synthetic sentences of more devices can be tested.

**Comment by gcampax** [comment]
Done
